name: CI
on:
  pull_request:
env:
  FORCE_COLOR: true
  NODE_VERSION: lts/*
jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Enable Corepack
        run: corepack enable
      - name: Use node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Test package
        run: yarn test
